# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sam/Desktop/obj-rasterizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sam/Desktop/obj-rasterizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sam/Desktop/obj-rasterizer/CMakeFiles /Users/sam/Desktop/obj-rasterizer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sam/Desktop/obj-rasterizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project1F

# Build rule for target.
project1F: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project1F
.PHONY : project1F

# fast build rule for target.
project1F/fast:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/build
.PHONY : project1F/fast

src/Camera.o: src/Camera.cxx.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cxx.o:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/Camera.cxx.o
.PHONY : src/Camera.cxx.o

src/Camera.i: src/Camera.cxx.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cxx.i:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/Camera.cxx.i
.PHONY : src/Camera.cxx.i

src/Camera.s: src/Camera.cxx.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cxx.s:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/Camera.cxx.s
.PHONY : src/Camera.cxx.s

src/Matrix.o: src/Matrix.cxx.o

.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cxx.o:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/Matrix.cxx.o
.PHONY : src/Matrix.cxx.o

src/Matrix.i: src/Matrix.cxx.i

.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cxx.i:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/Matrix.cxx.i
.PHONY : src/Matrix.cxx.i

src/Matrix.s: src/Matrix.cxx.s

.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cxx.s:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/Matrix.cxx.s
.PHONY : src/Matrix.cxx.s

src/main.o: src/main.cxx.o

.PHONY : src/main.o

# target to build an object file
src/main.cxx.o:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/main.cxx.o
.PHONY : src/main.cxx.o

src/main.i: src/main.cxx.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cxx.i:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/main.cxx.i
.PHONY : src/main.cxx.i

src/main.s: src/main.cxx.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cxx.s:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/main.cxx.s
.PHONY : src/main.cxx.s

src/reader.o: src/reader.cxx.o

.PHONY : src/reader.o

# target to build an object file
src/reader.cxx.o:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/reader.cxx.o
.PHONY : src/reader.cxx.o

src/reader.i: src/reader.cxx.i

.PHONY : src/reader.i

# target to preprocess a source file
src/reader.cxx.i:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/reader.cxx.i
.PHONY : src/reader.cxx.i

src/reader.s: src/reader.cxx.s

.PHONY : src/reader.s

# target to generate assembly for a file
src/reader.cxx.s:
	$(MAKE) -f CMakeFiles/project1F.dir/build.make CMakeFiles/project1F.dir/src/reader.cxx.s
.PHONY : src/reader.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... project1F"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/reader.o"
	@echo "... src/reader.i"
	@echo "... src/reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

